In [27]:
#Data 불러오기
import pandas as pd
csv=pd.read_csv('../Data/bmi.csv')
csv.head()

   height  weight   label
0     187      35    thin
1     144      68     fat
2     172      66  normal
3     156      54  normal
4     128      54     fat

In [28]:
#데이터 갯수
csv.count()

height    20000
weight    20000
label     20000
dtype: int64

In [29]:
#기본통계량
csv.describe()

             height        weight
count  20000.000000  20000.000000
mean     159.626350     57.419150
std       23.292565     13.193164
min      120.000000     35.000000
25%      139.000000     46.000000
50%      160.000000     57.000000
75%      180.000000     69.000000
max      200.000000     80.000000

In [30]:
#min/max 차이=> 정규화

In [31]:

csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   height  20000 non-null  int64
 1   weight  20000 non-null  int64
 2   label   20000 non-null  str
dtypes: int64(2), str(1)
memory usage: 468.9 KB

In [32]:
#label 종류 확인
csv['label'].unique()
csv['label'].value_counts()

label
fat       7791
thin      6328
normal    5881
Name: count, dtype: int64

In [33]:

sorted(csv['label'].unique())

['fat', 'normal', 'thin']

In [34]:
#data type
csv.dtypes
#object 사용 못함 notnull<-info

height    int64
weight    int64
label       str
dtype: object

#data 정규화

In [ ]:
#minmax 차이 많이남 정규화
#weight, height<-des
csv['weight']=csv['weight']/csv['weight'].max()
csv['height']=csv['height']/csv['height'].max()

In [36]:
csv.head()#label=category

   height  weight   label
0   0.935  0.4375    thin
1   0.720  0.8500     fat
2   0.860  0.8250  normal
3   0.780  0.6750  normal
4   0.640  0.6750     fat

In [37]:
#label 원핫인코딩(딕셔너리:key/value)
bclass={
    'thin':[1,0,0],
    'normal':[0,1,0],
    'fat':[0,0,1]
}
y=[]#if 필요없음
for v in csv['label']:
    #print(v)
    y.append(bclass[v])

y

[[1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 ...]

---
###훈련용과 테스트

In [38]:
#Train
x_train=csv[['height','weight']][:15000]
y_train=y[:15000]

In [39]:
x_train.tail()

       height  weight
14995   0.825  0.5000
14996   0.790  0.8875
14997   0.700  0.7375
14998   0.975  0.7000
14999   0.780  0.5000

In [40]:
len(x_train)

15000

In [41]:
y_train[:5]

[[1, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 0, 1]]

In [42]:
len(y_train)#리스트

15000

In [ ]:
#Test Data
x_test=csv[['height','weight']][15000:]
y_test=y[15000:]

In [44]:
x_test.tail()

       height  weight
19995   0.800  0.8375
19996   0.685  0.4375
19997   0.875  0.8375
19998   0.970  0.8500
19999   0.990  0.7875

In [45]:
y_test[:5]

[[0, 1, 0], [1, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 0]]

----
#### Deep Learning Model 만들기

In [ ]:
#입력층:2
#은닉층:512, activation='relu'
#출력층:3, activation='softmax'#<<<<<<타겟?의수
#loss:optimizer='rmsprop',loss='categorical_crossentropy'
from tensorflow import keras
from tensorflow.keras.layers import Input

model=keras.Sequential()#히든 레이어 만들기
model.add(Input(shape=(2,)))#튜플
# 첫 번째 은닉층
model.add(keras.layers.Dense(512, activation='relu'))

# 두 번째 은닉층 추가 
model.add(keras.layers.Dense(256, activation='relu'))

# model.add(keras.layers.Dense(512,activation='relu'))
model.add(keras.layers.Dense(3,activation='softmax'))

In [47]:
model.compile(
    optimizer='rmsprop',
    loss='categorical_crossentropy',#손실 함수   
    metrics=['accuracy']
)#오차계산

In [48]:
csv[['height','weight']]#두번쨰 은닉층은 갯수는 첫번째 은닉층 보다 작아야함

       height  weight
0       0.935  0.4375
1       0.720  0.8500
2       0.860  0.8250
3       0.780  0.6750
4       0.640  0.6750
...       ...     ...
19995   0.800  0.8375
19996   0.685  0.4375
19997   0.875  0.8375
19998   0.970  0.8500
19999   0.990  0.7875

[20000 rows x 2 columns]

In [ ]:
import numpy as np#시그모이드 2개만 가능
#verbose=0은 학습 과정 출력 여부, 0은 출력하지 않음, 1은 진행 바 형태로 출력, 2는 한 줄에 한 epoch마다 출력

In [50]:
model.fit(np.array(x_train), np.array(y_train), epochs=100)
model.evaluate(np.array(x_test), np.array(y_test))

Epoch 1/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 464us/step - accuracy: 0.7464 - loss: 0.6869
Epoch 2/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.9283 - loss: 0.3151
Epoch 3/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.9643 - loss: 0.2016
Epoch 4/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.9698 - loss: 0.1562
Epoch 5/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.9730 - loss: 0.1307
Epoch 6/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.9724 - loss: 0.1158
Epoch 7/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 563us/step - accuracy: 0.9737 - loss: 0.1062
Epoch 8/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.9743 - loss: 0.0982
Epoch 9/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.9751 - loss: 0.0917
Epoch 10/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.9756 - loss: 0.0867
Epoch 11/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.9758 - loss: 0.0835
Epoch 12/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.9753 - loss: 0.0793
Epoch 13/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.9764 - loss: 0.0765
Epoch 14/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step - accuracy: 0.9740 - loss: 0.0750
Epoch 15/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.9771 - loss: 0.0715
Epoch 16/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step - accuracy: 0.9773 - loss: 0.0699
Epoch 17/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.9757 - loss: 0.0685
Epoch 18/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.9767 - loss: 0.0673
Epoch 19/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.9773 - loss: 0.0654
Epoch 20/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.9770 - loss: 0.0651
Epoch 21/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.9779 - loss: 0.0634
Epoch 22/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.9771 - loss: 0.0628
Epoch 23/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 453us/step - accuracy: 0.9767 - loss: 0.0616
Epoch 24/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.9763 - loss: 0.0614
Epoch 25/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.9773 - loss: 0.0604
Epoch 26/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.9775 - loss: 0.0595
Epoch 27/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.9775 - loss: 0.0586
Epoch 28/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.9769 - loss: 0.0582
Epoch 29/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step - accuracy: 0.9774 - loss: 0.0578
Epoch 30/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9773 - loss: 0.0568
Epoch 31/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 479us/step - accuracy: 0.9775 - loss: 0.0565
Epoch 32/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - accuracy: 0.9775 - loss: 0.0567
Epoch 33/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - accuracy: 0.9783 - loss: 0.0555
Epoch 34/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - accuracy: 0.9775 - loss: 0.0553
Epoch 35/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - accuracy: 0.9778 - loss: 0.0556
Epoch 36/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 452us/step - accuracy: 0.9788 - loss: 0.0542
Epoch 37/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - accuracy: 0.9784 - loss: 0.0543
Epoch 38/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.9778 - loss: 0.0535
Epoch 39/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.9786 - loss: 0.0525
Epoch 40/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.9788 - loss: 0.0529
Epoch 41/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - accuracy: 0.9777 - loss: 0.0530
Epoch 42/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - accuracy: 0.9791 - loss: 0.0521
Epoch 43/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 534us/step - accuracy: 0.9788 - loss: 0.0521
Epoch 44/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.9783 - loss: 0.0526
Epoch 45/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - accuracy: 0.9789 - loss: 0.0514
Epoch 46/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.9784 - loss: 0.0518
Epoch 47/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - accuracy: 0.9767 - loss: 0.0518
Epoch 48/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9781 - loss: 0.0515
Epoch 49/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 453us/step - accuracy: 0.9777 - loss: 0.0511
Epoch 50/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - accuracy: 0.9771 - loss: 0.0512
Epoch 51/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 472us/step - accuracy: 0.9792 - loss: 0.0506
Epoch 52/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 538us/step - accuracy: 0.9797 - loss: 0.0501
Epoch 53/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.9777 - loss: 0.0508
Epoch 54/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.9779 - loss: 0.0503
Epoch 55/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.9786 - loss: 0.0499
Epoch 56/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 490us/step - accuracy: 0.9787 - loss: 0.0496
Epoch 57/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.9790 - loss: 0.0495
Epoch 58/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.9794 - loss: 0.0502
Epoch 59/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.9777 - loss: 0.0494
Epoch 60/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.9773 - loss: 0.0497
Epoch 61/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - accuracy: 0.9793 - loss: 0.0486
Epoch 62/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 499us/step - accuracy: 0.9793 - loss: 0.0486
Epoch 63/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - accuracy: 0.9796 - loss: 0.0492
Epoch 64/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.9788 - loss: 0.0488
Epoch 65/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.9790 - loss: 0.0484
Epoch 66/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.9790 - loss: 0.0489
Epoch 67/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 507us/step - accuracy: 0.9789 - loss: 0.0477
Epoch 68/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 596us/step - accuracy: 0.9782 - loss: 0.0476
Epoch 69/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 465us/step - accuracy: 0.9800 - loss: 0.0486
Epoch 70/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.9793 - loss: 0.0479
Epoch 71/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step - accuracy: 0.9794 - loss: 0.0486
Epoch 72/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - accuracy: 0.9787 - loss: 0.0470
Epoch 73/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - accuracy: 0.9792 - loss: 0.0479
Epoch 74/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 483us/step - accuracy: 0.9791 - loss: 0.0477
Epoch 75/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step - accuracy: 0.9783 - loss: 0.0471
Epoch 76/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9789 - loss: 0.0473
Epoch 77/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - accuracy: 0.9789 - loss: 0.0473
Epoch 78/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step - accuracy: 0.9787 - loss: 0.0480
Epoch 79/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - accuracy: 0.9797 - loss: 0.0469
Epoch 80/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.9778 - loss: 0.0479
Epoch 81/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - accuracy: 0.9791 - loss: 0.0478
Epoch 82/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.9790 - loss: 0.0472
Epoch 83/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9791 - loss: 0.0469
Epoch 84/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 706us/step - accuracy: 0.9795 - loss: 0.0464
Epoch 85/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 502us/step - accuracy: 0.9787 - loss: 0.0476
Epoch 86/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.9809 - loss: 0.0464
Epoch 87/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 472us/step - accuracy: 0.9808 - loss: 0.0456
Epoch 88/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - accuracy: 0.9804 - loss: 0.0460
Epoch 89/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step - accuracy: 0.9795 - loss: 0.0453
Epoch 90/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 482us/step - accuracy: 0.9799 - loss: 0.0458
Epoch 91/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step - accuracy: 0.9783 - loss: 0.0466
Epoch 92/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 469us/step - accuracy: 0.9804 - loss: 0.0460
Epoch 93/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.9802 - loss: 0.0461
Epoch 94/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.9794 - loss: 0.0458
Epoch 95/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - accuracy: 0.9800 - loss: 0.0452
Epoch 96/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - accuracy: 0.9784 - loss: 0.0458
Epoch 97/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 514us/step - accuracy: 0.9792 - loss: 0.0452
Epoch 98/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.9793 - loss: 0.0461
Epoch 99/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.9791 - loss: 0.0457
Epoch 100/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.9805 - loss: 0.0455
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - accuracy: 0.9788 - loss: 0.0456

[0.04556223005056381, 0.9787957668304443]

In [ ]:
model.predict(
    np.array(
    [
        [80, 180],
    ])
)