In [2]:
import pandas as pd
data=pd.read_csv('../Data/gpascore.csv')
data.head()

   admit    gre   gpa  rank
0      0  380.0  3.21     3
1      1  660.0  3.67     3
2      1  800.0  4.00     1
3      1  640.0  3.19     4
4      0  520.0  2.33     4

-admit: 대학원 합격 여부 (0,1)
-gre: 영어성적 (0~340)
-gpa: 학점 (0~10)
-rank:  지원한 대학원의 순위 (1~4) 
1이 가장 좋은 학교

In [3]:
data.info()#gre 결측치 있음

<class 'pandas.DataFrame'>
RangeIndex: 426 entries, 0 to 425
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   admit   426 non-null    int64
 1   gre     425 non-null    float64
 2   gpa     426 non-null    float64
 3   rank    426 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 13.4 KB

In [4]:
#결측치 제거#fillna()는 결측치를 채우는 함수, dropna()는 결측치가 있는 행을 제거하는 함수
data.dropna(inplace=True)

In [5]:
data.isnull().sum()#결측치 제거 확인

admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [12]:
#rank의 종류
data['rank'].unique()
data['rank'].value_counts()

rank
2    158
3    129
4     71
1     67
Name: count, dtype: int64

In [ ]:
sorted(data['rank'].unique())

[np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

In [15]:
data.head()

   admit    gre   gpa  rank
0      0  380.0  3.21     3
1      1  660.0  3.67     3
2      1  800.0  4.00     1
3      1  640.0  3.19     4
4      0  520.0  2.33     4

In [14]:
#target data 균등한지 확인
data['admit'].value_counts()

admit
0    224
1    201
Name: count, dtype: int64

train 데이터 만들기

In [16]:
x=data[['gre','gpa','rank']]
x.head()

     gre   gpa  rank
0  380.0  3.21     3
1  660.0  3.67     3
2  800.0  4.00     1
3  640.0  3.19     4
4  520.0  2.33     4

In [ ]:
y=data['admit']
y.head()#데이터 프레임/시리즈

0    0
1    1
2    1
3    1
4    0
Name: admit, dtype: int64

#DeepLearningModel만들기

In [ ]:
from tensorflow import keras
from tensorflow.keras.layers import Input

#입력층 : 3개(그레, gpa, rank)
#은닉층 : 32:하이퍼파라미터
#출력층 : 1개(합격 여부)<<0과 1로 표현/true/false로 표현
#활성화 함수 : sigmoid(0과 1 사이의 값을 출력하는 함수)/tanh(-1과 1 사이의 값을 출력하는 함수)/relu(0보다 작은 값은 0으로, 0보다 큰 값은 그대로 출력하는 함수)/
#softmax(출력값의 합이 1이 되도록 하는 함수, 다중 클래스 분류에서 사용)/leaky relu(0보다 작은 값은 작은 음수로, 0보다 큰 값은 그대로 출력하는 함수)/elu(0보다 작은 값은 지수 함수로, 0보다 큰 값은 그대로 출력하는 함수)

model=keras.Sequential()#히든 레이어 만들기
model.add(Input(shape=(3,)))#튜플
model.add(keras.layers.Dense(32,activation='tanh'))#숫자계산? #은닉층:2의 배수(입력층보다 많아야함)
model.add(keras.layers.Dense(1,activation='sigmoid'))#1
#model.add(keras.layers.Dense(1,activation='softmax'))#2

In [ ]:
model.compile(
    optimizer='adam',#최적화 알고리즘 #하이퍼파라미터
    loss='binary_crossentropy',#손실 함수   
    metrics=['accuracy']
)#오차계산

#optimizer : 모델의 가중치를 업데이트하는 방법을 결정하는 알고리즘:learning rate(학습률)을 알맞게 수정해줌
#:adam,adagrad,rmsprop,sgd,adadelta 등 다양한 최적화 알고리즘이 존재

#loss : 모델의 예측값과 실제값의 차이를 계산하는 함수
#:손실함수:binary_crossentropy(이진 분류에서 사용),categorical_crossentropy(다중 클래스 분류에서 사용),mean_squared_error(회귀 문제에서 사용) 등 다양한 손실 함수가 존재

#metrics : 모델의 성능을 평가하는 지표  
#:accuracy(정확도),precision(정밀도),recall(재현율),f1_score(f1 점수) 등 다양한 평가 지표가 존재

In [ ]:
#학습시키기
x
# 딥러닝 어레이

       gre   gpa  rank
0    380.0  3.21     3
1    660.0  3.67     3
2    800.0  4.00     1
3    640.0  3.19     4
4    520.0  2.33     4
..     ...   ...   ...
421  750.0  3.44     4
422  710.0  3.66     4
423  450.0  3.25     4
424  760.0  3.76     2
425  710.0  3.82     3

[425 rows x 3 columns]

In [ ]:
import numpy as np
#verbose=0은 학습 과정 출력 여부, 0은 출력하지 않음, 1은 진행 바 형태로 출력, 2는 한 줄에 한 epoch마다 출력
model.fit(np.array(x),np.array(y),epochs=1000)#학습시키기, epochs는 학습 횟수, verbose는 학습 과정 출력 여부
#많이 반복 epochs=1000<-100

Epoch 1/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5271 - loss: 1.0344
Epoch 2/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5271 - loss: 0.8993
Epoch 3/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5271 - loss: 0.7972
Epoch 4/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5271 - loss: 0.7339
Epoch 5/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5271 - loss: 0.7035
Epoch 6/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5271 - loss: 0.6950
Epoch 7/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5271 - loss: 0.6910
Epoch 8/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5271 - loss: 0.6839
Epoch 9/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5271 - loss: 0.6791
Epoch 10/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5553 - loss: 0.6854
Epoch 11/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5271 - loss: 0.6763
Epoch 12/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5271 - loss: 0.6691
Epoch 13/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5482 - loss: 0.6696
Epoch 14/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6259 - loss: 0.6679
Epoch 15/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6047 - loss: 0.6697
Epoch 16/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6282 - loss: 0.6637
Epoch 17/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6235 - loss: 0.6667
Epoch 18/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6000 - loss: 0.6625
Epoch 19/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6000 - loss: 0.6625
Epoch 20/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5929 - loss: 0.6653
Epoch 21/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6188 - loss: 0.6636
Epoch 22/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5953 - loss: 0.6680
Epoch 23/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5812 - loss: 0.6758
Epoch 24/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6165 - loss: 0.6619
Epoch 25/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6400 - loss: 0.6645
Epoch 26/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6024 - loss: 0.6696
Epoch 27/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5976 - loss: 0.6631
Epoch 28/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6424 - loss: 0.6597
Epoch 29/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6094 - loss: 0.6659
Epoch 30/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5976 - loss: 0.6730
Epoch 31/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6165 - loss: 0.6640
Epoch 32/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6000 - loss: 0.6673
Epoch 33/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6094 - loss: 0.6678
Epoch 34/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6376 - loss: 0.6647
Epoch 35/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6188 - loss: 0.6595
Epoch 36/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6165 - loss: 0.6588
Epoch 37/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6400 - loss: 0.6589
Epoch 38/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6024 - loss: 0.6668
Epoch 39/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5976 - loss: 0.6680
Epoch 40/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6165 - loss: 0.6566
Epoch 41/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6165 - loss: 0.6606
Epoch 42/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6306 - loss: 0.6561
Epoch 43/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6047 - loss: 0.6590
Epoch 44/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6071 - loss: 0.6560
Epoch 45/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5929 - loss: 0.6570
Epoch 46/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6118 - loss: 0.6547
Epoch 47/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6165 - loss: 0.6532
Epoch 48/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6188 - loss: 0.6532
Epoch 49/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6165 - loss: 0.6531
Epoch 50/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5929 - loss: 0.6658
Epoch 51/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6047 - loss: 0.6575
Epoch 52/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6235 - loss: 0.6566
Epoch 53/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6071 - loss: 0.6589
Epoch 54/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6447 - loss: 0.6595
Epoch 55/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6306 - loss: 0.6578
Epoch 56/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6165 - loss: 0.6573
Epoch 57/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6024 - loss: 0.6534
Epoch 58/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6353 - loss: 0.6530
Epoch 59/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6188 - loss: 0.6526
Epoch 60/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6141 - loss: 0.6574
Epoch 61/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6235 - loss: 0.6496
Epoch 62/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6235 - loss: 0.6530
Epoch 63/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6118 - loss: 0.6582
Epoch 64/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6165 - loss: 0.6554
Epoch 65/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6517
Epoch 66/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6259 - loss: 0.6517
Epoch 67/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6141 - loss: 0.6498
Epoch 68/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6000 - loss: 0.6509
Epoch 69/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6118 - loss: 0.6545
Epoch 70/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6235 - loss: 0.6594
Epoch 71/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6118 - loss: 0.6574
Epoch 72/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6306 - loss: 0.6501
Epoch 73/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6188 - loss: 0.6551
Epoch 74/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6306 - loss: 0.6504
Epoch 75/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6259 - loss: 0.6523
Epoch 76/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6353 - loss: 0.6558
Epoch 77/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6165 - loss: 0.6551
Epoch 78/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6329 - loss: 0.6491
Epoch 79/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6165 - loss: 0.6491
Epoch 80/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6282 - loss: 0.6518
Epoch 81/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6353 - loss: 0.6489
Epoch 82/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6047 - loss: 0.6630
Epoch 83/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6165 - loss: 0.6470
Epoch 84/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6447
Epoch 85/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6376 - loss: 0.6531
Epoch 86/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6259 - loss: 0.6506
Epoch 87/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6188 - loss: 0.6466
Epoch 88/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6071 - loss: 0.6482
Epoch 89/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6165 - loss: 0.6476
Epoch 90/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6329 - loss: 0.6448
Epoch 91/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6329 - loss: 0.6453
Epoch 92/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6474
Epoch 93/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6235 - loss: 0.6578
Epoch 94/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5482 - loss: 0.6768
Epoch 95/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6329 - loss: 0.6489
Epoch 96/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6188 - loss: 0.6539
Epoch 97/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6500
Epoch 98/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6165 - loss: 0.6454
Epoch 99/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6329 - loss: 0.6460
Epoch 100/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6259 - loss: 0.6429

In [24]:
model.evaluate(np.array(x),np.array(y))

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6447 - loss: 0.6475

[0.6474812626838684, 0.6447058916091919]

#예측하기#에포크 높이면 좋아짐 데이터 많아야함#시그모이드 0.5이상 갈수 있음#영어점수,학점 중요

In [ ]:
#gre:700, 학점:3.7, rank:4인 학교
model.predict(np.array([[700,3.7,1],[700,3.7,2],[700,3.7,3],[700,3.7,4]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step

array([[0.58857536],
       [0.5845755 ],
       [0.57159317],
       [0.53297585]], dtype=float32)

In [ ]:
#예측하기
#gre:400,gra:2.2,rank:1인 학교
model.predict(np.array([[400,2.2,1],[400,2.2,2],[400,2.2,3],[400,2.2,4]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

array([[0.5471856 ],
       [0.47307467],
       [0.35817966],
       [0.27162218]], dtype=float32)